# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hello.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hello.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\x12\x05hello\")\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"3\n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"\x1d\n\x0cStoryRequest\x12\r\n\x05topic\x18\x01 \x01(\t\"3\n\nStoryChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x14\n\x0c\x63hunk_number\x18\x02 \x01(\x05\"<\n\x07LogLine\x12\r\n\x05level\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"^\n\nLogSummary\x12\x13\n\x0btotal_lines\x18\x01 \x01(\x05\x12\x12\n\ninfo_count\x18\x02 \x01(\x05\x12\x12\n\nwarn_count\x18\x03 \x01(\x05\x12\x13\n\x0b\x65rror_count\x18\x04 \x01(\x05\")\n\x0b\x43hatMessage\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\'\n\tChatReply\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t2\xdc\x01\n\x07Greeter\x12\x35\n\x08SayHello\x12\x13.hello.HelloRequest\x1a\x14.hello.HelloResponse\x12\x35\n\tTellStory\x12\x13.hello.StoryRequest\x1a\x11.hello.StoryChunk0\x01\x12\x31\n\nUploadLogs\x12\x0e.hello.LogLine\x1a\x11.hello.LogSummary(\x01\x12\x30\n\x04\x43hat\x12\x12.hello.ChatMessage\x1a\x10.hello.ChatReply(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=22
  _globals['_HELLOREQUEST']._serialized_end=63
  _globals['_HELLORESPONSE']._serialized_start=65
  _globals['_HELLORESPONSE']._serialized_end=116
  _globals['_STORYREQUEST']._serialized_start=118
  _globals['_STORYREQUEST']._serialized_end=147
  _globals['_STORYCHUNK']._serialized_start=149
  _globals['_STORYCHUNK']._serialized_end=200
  _globals['_LOGLINE']._serialized_start=202
  _globals['_LOGLINE']._serialized_end=262
  _globals['_LOGSUMMARY']._serialized_start=264
  _globals['_LOGSUMMARY']._serialized_end=358
  _globals['_CHATMESSAGE']._serialized_start=360
  _globals['_CHATMESSAGE']._serialized_end=401
  _globals['_CHATREPLY']._serialized_start=403
  _globals['_CHATREPLY']._serialized_end=442
  _globals['_GREETER']._serialized_start=445
  _globals['_GREETER']._serialized_end=665
# @@protoc_insertion_point(module_scope)
